### PR TITLE
Crusader sword in shop

### PR DESCRIPTION
**Pull request by PYROTEKNIK**
I feel like this weapon is too much fun to just leave it gone forever. I think this would be a good prize for the crusaders since they won and their original reward was rescinded.

### CODE REVIEW

**Comment by swampservers** [comment]
Need to remove SetupMove (or refactor it with the flappy fedora - make SWEP:SetupMove())

**Comment by PYROTEKNIK** [comment]
Good idea. I will work on that

**Comment by PYROTEKNIK** [comment]
sorry about the pissing around, i didn't realize you had implemented it already

**Comment by swampservers** [comment]
You have a KeyRelease hook in here that does literally nothing and the check is run every time any player presses any key.

**Comment by PYROTEKNIK** [comment]
> You have a KeyRelease hook in here that does literally nothing and the check is run every time any player presses any key.

there was a float jump thing in there. did you remove it during the war or was it me?

**Comment by swampservers** [comment]
> > You have a KeyRelease hook in here that does literally nothing and the check is run every time any player presses any key.
> 
> there was a float jump thing in there. did you remove it during the war or was it me?

Maybe IDK, either way, it looks like you deleted all of the jump stuff which was a good idea

**Pull request merged**
