### PR TITLE
Soundcloud Support

### PR DESCRIPTION
**Pull request by Noztik**
html code: view-source:http://backdoorcinema.net/cinema/soundcloud.html

use this for the title `string.match( body, "<title>(.*) by.*</title>" ) or "(Unknown)"`

### CODE REVIEW

**Comment by swampservers** [comment]
Are you sure we need Flash for this? It doesn't work anymore lol

**Comment by Noztik** [comment]
you don't need flash but I don't know what your function is to check for chromium

**Comment by swampservers** [comment]
EmbeddedCheckChromium

**Comment by swampservers** [comment]
Thanks! I'm going to merge this then change some things, please take a look once i commit

**Pull request merged**
