### PR TITLE
Fix rumble seek

### PR DESCRIPTION
**Pull request by swamproyal**

### CODE REVIEW

**Comment by swamproyal** [comment]
@WinterPhoenix could you accept this one asap

**Comment by swamproyal** [comment]
Also, can you add rumble to the video request browser home page?

**Comment by WinterPhoenix** [comment]
querySelectorAll is slow. Just find the video player and persist it as a var; no need to scan the entire page every time the volume changes or the video needs to be seeked

**Comment by swamproyal** [comment]
> querySelectorAll is slow. Just find the video player and persist it as a var; no need to scan the entire page every time the volume changes or the video needs to be seeked

I've simplified it and addressed this concern.

**Comment by swamproyal** [comment]
@WinterPhoenix does it look good to you?

**Review by WinterPhoenix — APPROVED** [review]

**Comment by WinterPhoenix** [comment]
There you go. lgtm

**Pull request merged**
