### PR TITLE
Remove invalid bumpmap in maze model texture

### PR DESCRIPTION
**Pull request by swamproyal**
This fixes the maze wall texture on Linux

### CODE REVIEW

**Comment by WinterPhoenix** [comment]
I think we may be changing this in Map v4. I'll wait for @PYROTEKNIK's input

**Comment by PYROTEKNIK** [comment]
> This fixes the maze wall texture on Linux

what is the issue on linux?

**Comment by swamproyal** [comment]
> > This fixes the maze wall texture on Linux
> 
> what is the issue on linux?

The texture doesn't work. It's black.

**Comment by swamproyal** [comment]
It's not a new issue either, it's been this way since the v3 release in 2020

**Comment by PYROTEKNIK** [comment]
I think we should wait until the next map version to look at this. The upcoming version uses lightmappedgeneric with fake lightmaps

**Comment by WinterPhoenix** [comment]
Not gonna touch it in that case. v4 is close

**Pull request closed without merging**
