### PR TITLE
Airgun

### PR DESCRIPTION
**Pull request by Milwacko**

### CODE REVIEW

**Comment by chev2** [comment]
you should probably change every instance of weapon:EmitSound to weapon:ExtEmitSound

also that crowbar sound is a bit annoying but if it's the best we have for a proper sound then I guess it's ok

**Comment by swampservers** [comment]
Noz told me he has a new version of the swep file (this one is too big and all that is just copied from some crappy workshop item), please update

**Comment by swampservers** [comment]
waiting for Noz's code

**Comment by swampservers** [comment]
New pr is opened

**Pull request closed without merging**
